// <auto-generated />
using ConsoleApp1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    partial class ECommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ConsoleApp1.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = "acc1",
                            Name = "John Smith",
                            Password = "9F86D081884C7D659A2FEAA0C55AD015A3BF4F1B2B0B822CD15D6C15B0F00A08"
                        },
                        new
                        {
                            Id = "acc2",
                            Name = "Jane Jones",
                            Password = "9F86D081884C7D659A2FEAA0C55AD015A3BF4F1B2B0B822CD15D6C15B0F00A08"
                        });
                });

            modelBuilder.Entity("ConsoleApp1.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("RetailPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPrice = 0.69999999999999996,
                            Name = "Pedigree Chum",
                            RetailPrice = 1.4199999999999999
                        },
                        new
                        {
                            Id = 2,
                            CostPrice = 0.59999999999999998,
                            Name = "Knife",
                            RetailPrice = 1.3100000000000001
                        },
                        new
                        {
                            Id = 3,
                            CostPrice = 0.75,
                            Name = "Fork",
                            RetailPrice = 1.5700000000000001
                        },
                        new
                        {
                            Id = 4,
                            CostPrice = 0.90000000000000002,
                            Name = "Spaghetti",
                            RetailPrice = 1.9199999999999999
                        },
                        new
                        {
                            Id = 5,
                            CostPrice = 0.65000000000000002,
                            Name = "Cheddar Cheese",
                            RetailPrice = 1.47
                        },
                        new
                        {
                            Id = 6,
                            CostPrice = 15.199999999999999,
                            Name = "Bean bag",
                            RetailPrice = 32.200000000000003
                        },
                        new
                        {
                            Id = 7,
                            CostPrice = 22.300000000000001,
                            Name = "Bookcase",
                            RetailPrice = 46.32
                        },
                        new
                        {
                            Id = 8,
                            CostPrice = 55.200000000000003,
                            Name = "Table",
                            RetailPrice = 134.80000000000001
                        },
                        new
                        {
                            Id = 9,
                            CostPrice = 43.700000000000003,
                            Name = "Chair",
                            RetailPrice = 110.2
                        },
                        new
                        {
                            Id = 10,
                            CostPrice = 3.2000000000000002,
                            Name = "Doormat",
                            RetailPrice = 7.4000000000000004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
